name: denovo_assembly
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - numpy
  - pandas
  - scipy
  - matplotlib
  - fastqc
  - trimmomatic
  - bwa
  - samtools
  - bcftools
  - quast
  - spades
  - pilon
  - prokka
  - artemis

tasks:
  - name: Setup Conda Env
    init: conda env create -f environment.yml || conda env update -f environment.yml
    command: conda activate your-env-name

  